{
 "title": "student_api_dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of Student Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "student_records_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Error Rate (non-2xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(http_errors_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}